manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: ronan
      url-base: https://github.com/RonanB96/

  projects:
    - name: sdk-nrf
      remote: ncs
      path: nrf
      revision: v3.0.2
      import:
        # Import the NCS manifest with module path prefix
        file: west.yml
        path-prefix: modules
    # Override Zephyr with your specific commit/branch
    - name: zephyr
      remote: ronan
      path: modules/zephyr
      revision: 825150eccf5b33fd6f120cec9bdbad8dc5bde402
      west-commands: scripts/west-commands.yml

  self:
    path: app
