#!/usr/bin/env bash
# resolve_serial_port.sh — discover and cache the Thingy:52 UART device node.
#
# /dev/ttyUSB* numbers change across plug/unplug. The resolved port is stored in
# .hardware/session for the current working session (gitignored).
#
# Usage:
#   SERIAL_PORT=$(scripts/resolve_serial_port.sh)
#   eval "$(scripts/resolve_serial_port.sh --export)"
#   source .hardware/session
#   scripts/resolve_serial_port.sh --refresh

SESSION_FILE="${HARDWARE_SESSION:-.hardware/session}"

save_session_port() {
    local port="$1"
    mkdir -p "$(dirname "$SESSION_FILE")"
    cat >"$SESSION_FILE" <<EOF
# Auto-generated by scripts/resolve_serial_port.sh — do not commit.
SERIAL_PORT=$port
EOF
}

read_session_port() {
    if [[ ! -f "$SESSION_FILE" ]]; then
        return 1
    fi
    local port
    port=$(grep -E '^SERIAL_PORT=' "$SESSION_FILE" | tail -1 | cut -d= -f2-)
    if [[ -n "$port" && -e "$port" ]]; then
        echo "$port"
        return 0
    fi
    return 1
}

discover_serial_port() {
    local port=""

    if command -v nrfutil >/dev/null 2>&1; then
        port=$(nrfutil device list 2>&1 | awk '
            /^Ports[[:space:]]/ { port = $2 }
            /serialPorts/ {
                if (port != "") {
                    print port
                    exit
                }
            }
        ')
        if [[ -n "$port" && -e "$port" ]]; then
            echo "$port"
            return 0
        fi
    fi

    port=$(ls /dev/serial/by-id/usb-FTDI_TTL232R-* 2>/dev/null | head -1)
    if [[ -n "$port" && -e "$port" ]]; then
        echo "$port"
        return 0
    fi

    return 1
}

resolve_serial_port() {
    local refresh="${1:-0}"
    local port=""

    if [[ -n "${SERIAL_PORT:-}" ]]; then
        if [[ "$refresh" == "1" ]]; then
            save_session_port "$SERIAL_PORT"
        fi
        echo "$SERIAL_PORT"
        return 0
    fi

    if [[ "$refresh" != "1" ]]; then
        if port=$(read_session_port); then
            echo "$port"
            return 0
        fi
    fi

    if ! port=$(discover_serial_port); then
        return 1
    fi

    save_session_port "$port"
    echo "$port"
}

usage() {
    cat <<EOF
Usage: $(basename "$0") [--export|--refresh]

Discover the Thingy:52 UART port and cache it in $SESSION_FILE.
Pass --refresh to ignore the cached value and rediscover.
EOF
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    mode="print"
    refresh=0

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --export)
                mode="export"
                shift
                ;;
            --refresh)
                refresh=1
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option: $1" >&2
                usage >&2
                exit 2
                ;;
        esac
    done

    if ! port=$(resolve_serial_port "$refresh"); then
        echo "FAIL: could not resolve UART port (set SERIAL_PORT or replug the FTDI cable)" >&2
        exit 1
    fi

    case "$mode" in
        export)
            printf 'export SERIAL_PORT=%q\n' "$port"
            ;;
        print)
            echo "$port"
            ;;
    esac
fi
